services:
  socks-proxy:
    image: socks-proxy
    build:
      dockerfile: Dockerfile-socks
    user: ubuntu
    ports:
      - 2280:${JUMP_PORT}
    restart: unless-stopped
    command: ["-o", "ExitOnForwardFailure=yes", "-o", "StrictHostKeyChecking=no", "-o", "UserKnownHostsFile=/dev/null", "-ND", "socks-proxy:${JUMP_PORT}", $JUMP_HOST, "-l", $JUMP_USER]

  http-proxy:
    image: http-proxy
    build:
      dockerfile: Dockerfile-http
    ports:
      - 9080:9080
    restart: unless-stopped
    command: ["hpts",  "-s", "socks-proxy:${JUMP_PORT}",  "-l", "http-proxy", "-p", "9080"]
